### ISSUE TITLE
Potential to Switch to Unreal Engine 4?

### ISSUE THREAD

**Issue by james7132** [james7132/GensoShojokosen#11]
Unreal Engine 4 is now free, and with a potential to be much better suited for a large scale game like this.

There are a number of things we've considered that may be limited in Unity Free that are easy to do in UE4.

**Comment by KazeSenshi** [comment]
For me Unity3d is good for big projects like this one too. What kind of things that are limited to Unity Pro that are necessary to create a Smash bros-ish game?

**Comment by james7132** [comment]
It's largely the visuals. The fact that RenderTextures are Pro only removes any possibility for any graphics post processing, despite being a standard OpenGL 1.1 and DirectX 8 feature (both of which are far outdated and simple to do in virtually any other 3D game engine. That includes any anti-aliasing, which means sharp unruly edges on almost every rendered object.

Threading support is non-existent in Unity at the moment which might be useful for certain calculations.

I am still researching to see if this is a good idea or not. Generally speaking, we will be trading complexity of development for polish on the final product.

**Comment by KazeSenshi** [comment]
I think that you can enable anti-aliasing at the project's Quality Settings. Doesn't Unity have [multithreading](https://www.assetstore.unity3d.com/en/#!/content/15717) using that coroutines thing? And really it doesn't support post rendering but this is only useful for things like reflections and heat distortion, isn't that? I don't remember to see things like this on SSB.

In my opinion, in this case, there is no reason to change a project that is already started on Unity3D to UE4 but it would be interesting to play with UE4 in some next new project. Also it seems that they will release some big news about Unity today. Lets see what will happpen :P

**Comment by KazeSenshi** [comment]
Ahhh now those Unity Pro feature are for [free](https://unity3d.com/get-unity) :)

**Comment by james7132** [comment]
Indeed, and without the unnecessary complexity of UE4. Marking as closed.

**Comment by avatarxargo** [comment]
I actually did some stuff in UE4 already and I just love that environment, but I can't really assess how it will work compared to what Unity offers. Given we already do have unity framework it might be better to stay in Unity.
