### ISSUE TITLE
Choose a default pattern to define and process keyboard/joystick input commands

### ISSUE THREAD

**Issue by KazeSenshi** [james7132/GensoShojokosen#6]
Hello guys, I think that now it is a good moment to define how we will implement the input processing than to needing to change it later. I thought that a good input system should have:

* A way to support joysticks like the one from XBox;
* A way to let the user define the buttons configuration;
* More than 2 players on the same computer (co-op);

After looking in google I found this open-source library that seems to have all these features, what do you guys think about it?

http://forum.unity3d.com/threads/free-custom-input-manager.223321/

Cheers

**Comment by james7132** [comment]
Input Manager is added and is our standard for Input now.
